# Generated by Django 3.2.5 on 2021-11-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0003_user_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
